// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"scalify-pp-cli/internal/cli"
	"scalify-pp-cli/internal/cliutil"
	"scalify-pp-cli/internal/client"
	"scalify-pp-cli/internal/config"
	"scalify-pp-cli/internal/mcp/cobratree"
	"scalify-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("blogs_get_posts",
			mcplib.WithDescription("GET /blogs/{id}/posts/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/blogs/{id}/posts/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("blogs_list_authors",
			mcplib.WithDescription("GET /blogs/authors. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/blogs/authors", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("blogs_list_categories",
			mcplib.WithDescription("GET /blogs/categories. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/blogs/categories", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("blogs_list_posts",
			mcplib.WithDescription("GET /blogs/posts. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/blogs/posts", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("blogs_list_url_slug_exists",
			mcplib.WithDescription("GET /blogs/posts/url-slug-exists. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/blogs/posts/url-slug-exists", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("businesses_create_businesses",
			mcplib.WithDescription("POST /businesses. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/businesses", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("businesses_delete_businesses",
			mcplib.WithDescription("DELETE /businesses/{id}. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/businesses/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("businesses_get_businesses",
			mcplib.WithDescription("GET /businesses/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/businesses/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("businesses_list_businesses",
			mcplib.WithDescription("GET /businesses. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/businesses", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("businesses_update_businesses",
			mcplib.WithDescription("PUT /businesses/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/businesses/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("calendars_create_appointments",
			mcplib.WithDescription("POST /calendars/events/appointments. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/calendars/events/appointments", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("calendars_create_calendars",
			mcplib.WithDescription("POST /calendars. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/calendars", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("calendars_delete_calendars",
			mcplib.WithDescription("DELETE /calendars/{id}. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/calendars/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("calendars_get_calendars",
			mcplib.WithDescription("GET /calendars/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/calendars/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("calendars_get_free_slots",
			mcplib.WithDescription("GET /calendars/{id}/free-slots. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/calendars/{id}/free-slots", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("calendars_list_calendars",
			mcplib.WithDescription("GET /calendars. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/calendars", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("calendars_list_events",
			mcplib.WithDescription("GET /calendars/events. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/calendars/events", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("calendars_update_calendars",
			mcplib.WithDescription("PUT /calendars/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/calendars/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("campaigns_list_campaigns",
			mcplib.WithDescription("GET /campaigns. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/campaigns", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_create_contacts",
			mcplib.WithDescription("POST /contacts. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/contacts", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_create_notes",
			mcplib.WithDescription("POST /contacts/{id}/notes. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/contacts/{id}/notes", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_create_tags",
			mcplib.WithDescription("POST /contacts/{id}/tags. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/contacts/{id}/tags", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_create_tasks",
			mcplib.WithDescription("POST /contacts/{id}/tasks. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/contacts/{id}/tasks", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_create_upsert",
			mcplib.WithDescription("POST /contacts/upsert. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/contacts/upsert", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_create_workflow",
			mcplib.WithDescription("POST /contacts/{id}/workflow/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/contacts/{id}/workflow/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_delete_contacts",
			mcplib.WithDescription("DELETE /contacts/{id}. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/contacts/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_delete_tags",
			mcplib.WithDescription("DELETE /contacts/{id}/tags. Required: id. Optional: body. Destructive."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/contacts/{id}/tags", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_get_appointments",
			mcplib.WithDescription("GET /contacts/{id}/appointments. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts/{id}/appointments", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_get_contacts",
			mcplib.WithDescription("GET /contacts/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_get_notes",
			mcplib.WithDescription("GET /contacts/{id}/notes. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts/{id}/notes", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_get_tasks",
			mcplib.WithDescription("GET /contacts/{id}/tasks. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts/{id}/tasks", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_list_contacts",
			mcplib.WithDescription("GET /contacts. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/contacts", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("contacts_update_contacts",
			mcplib.WithDescription("PUT /contacts/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/contacts/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("conversations_create_conversations",
			mcplib.WithDescription("POST /conversations. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/conversations", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("conversations_create_inbound",
			mcplib.WithDescription("POST /conversations/messages/inbound. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/conversations/messages/inbound", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("conversations_create_messages",
			mcplib.WithDescription("POST /conversations/messages. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/conversations/messages", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("conversations_get_conversations",
			mcplib.WithDescription("GET /conversations/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/conversations/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("conversations_get_messages",
			mcplib.WithDescription("GET /conversations/{id}/messages. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/conversations/{id}/messages", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("conversations_get_messages_2",
			mcplib.WithDescription("GET /conversations/messages/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/conversations/messages/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("conversations_list_search",
			mcplib.WithDescription("GET /conversations/search. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/conversations/search", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("conversations_update_status",
			mcplib.WithDescription("PUT /conversations/messages/{id}/status. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/conversations/messages/{id}/status", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("courses_list_courses",
			mcplib.WithDescription("GET /courses. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/courses", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("documents_create_send",
			mcplib.WithDescription("POST /documents/{id}/send. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/documents/{id}/send", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("documents_delete_documents",
			mcplib.WithDescription("DELETE /documents/{id}. Required: id. Optional: params. Destructive."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/documents/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("documents_get_documents",
			mcplib.WithDescription("GET /documents/{id}. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/documents/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("documents_list_documents",
			mcplib.WithDescription("GET /documents. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/documents", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("emails_list_emails",
			mcplib.WithDescription("GET /emails. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/emails", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("forms_list_forms",
			mcplib.WithDescription("GET /forms. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/forms", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("forms_list_submissions",
			mcplib.WithDescription("GET /forms/submissions. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/forms/submissions", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("funnels_list_funnels",
			mcplib.WithDescription("GET /funnels. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/funnels", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("funnels_list_list",
			mcplib.WithDescription("GET /funnels/funnel/list. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/funnels/funnel/list", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("funnels_list_page",
			mcplib.WithDescription("GET /funnels/page. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/funnels/page", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_create_estimate",
			mcplib.WithDescription("POST /invoices/estimate. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/invoices/estimate", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_create_invoices",
			mcplib.WithDescription("POST /invoices. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/invoices", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_create_record_payment",
			mcplib.WithDescription("POST /invoices/{id}/record-payment. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/invoices/{id}/record-payment", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_create_send",
			mcplib.WithDescription("POST /invoices/{id}/send. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/invoices/{id}/send", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_create_send_2",
			mcplib.WithDescription("POST /invoices/estimate/{id}/send. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/invoices/estimate/{id}/send", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_create_void",
			mcplib.WithDescription("POST /invoices/{id}/void. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/invoices/{id}/void", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_delete_estimate",
			mcplib.WithDescription("DELETE /invoices/estimate/{id}. Required: id. Optional: params. Destructive."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/invoices/estimate/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_delete_invoices",
			mcplib.WithDescription("DELETE /invoices/{id}. Required: id. Optional: params. Destructive."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/invoices/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_get_estimate",
			mcplib.WithDescription("GET /invoices/estimate/{id}. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/invoices/estimate/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_get_invoices",
			mcplib.WithDescription("GET /invoices/{id}. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/invoices/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_list_estimate",
			mcplib.WithDescription("GET /invoices/estimate. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/invoices/estimate", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_list_invoices",
			mcplib.WithDescription("GET /invoices. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/invoices", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_update_estimate",
			mcplib.WithDescription("PUT /invoices/estimate/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/invoices/estimate/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("invoices_update_invoices",
			mcplib.WithDescription("PUT /invoices/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/invoices/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("links_list_links",
			mcplib.WithDescription("GET /links. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/links", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("locations_create_custom_fields",
			mcplib.WithDescription("POST /locations/{id}/customFields. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/locations/{id}/customFields", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_create_custom_values",
			mcplib.WithDescription("POST /locations/{id}/customValues. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/locations/{id}/customValues", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_create_tags",
			mcplib.WithDescription("POST /locations/{id}/tags. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/locations/{id}/tags", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_delete_custom_fields",
			mcplib.WithDescription("DELETE /locations/{id}/customFields/{id}. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/locations/{id}/customFields/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_delete_custom_values",
			mcplib.WithDescription("DELETE /locations/{id}/customValues/{id}. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/locations/{id}/customValues/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_delete_tags",
			mcplib.WithDescription("DELETE /locations/{id}/tags/{id}. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/locations/{id}/tags/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_get_custom_fields",
			mcplib.WithDescription("GET /locations/{id}/customFields. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/locations/{id}/customFields", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_get_custom_values",
			mcplib.WithDescription("GET /locations/{id}/customValues. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/locations/{id}/customValues", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_get_locations",
			mcplib.WithDescription("GET /locations/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/locations/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_get_tags",
			mcplib.WithDescription("GET /locations/{id}/tags. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/locations/{id}/tags", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_list_locations",
			mcplib.WithDescription("GET /locations."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/locations", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("locations_list_search",
			mcplib.WithDescription("GET /locations/search. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/locations/search", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("locations_update_custom_fields",
			mcplib.WithDescription("PUT /locations/{id}/customFields/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/locations/{id}/customFields/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_update_custom_values",
			mcplib.WithDescription("PUT /locations/{id}/customValues/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/locations/{id}/customValues/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_update_locations",
			mcplib.WithDescription("PUT /locations/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/locations/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("locations_update_tags",
			mcplib.WithDescription("PUT /locations/{id}/tags/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/locations/{id}/tags/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("medias_delete_medias",
			mcplib.WithDescription("DELETE /medias/{id}. Required: id. Optional: params. Destructive."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/medias/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("medias_list_files",
			mcplib.WithDescription("GET /medias/files. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/medias/files", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("objects_create_records",
			mcplib.WithDescription("POST /objects/{id}/records. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/objects/{id}/records", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("objects_delete_records",
			mcplib.WithDescription("DELETE /objects/{id}/records/{id}. Required: id. Optional: params. Destructive."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/objects/{id}/records/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("objects_get_objects",
			mcplib.WithDescription("GET /objects/{id}. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("objects_get_records",
			mcplib.WithDescription("GET /objects/{id}/records. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects/{id}/records", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("objects_get_records_2",
			mcplib.WithDescription("GET /objects/{id}/records/{id}. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects/{id}/records/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("objects_list_objects",
			mcplib.WithDescription("GET /objects. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/objects", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("objects_update_records",
			mcplib.WithDescription("PUT /objects/{id}/records/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/objects/{id}/records/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("opportunities_create_opportunities",
			mcplib.WithDescription("POST /opportunities. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/opportunities", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("opportunities_delete_opportunities",
			mcplib.WithDescription("DELETE /opportunities/{id}. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/opportunities/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("opportunities_get_opportunities",
			mcplib.WithDescription("GET /opportunities/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/opportunities/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("opportunities_list_pipelines",
			mcplib.WithDescription("GET /opportunities/pipelines. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/opportunities/pipelines", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("opportunities_list_search",
			mcplib.WithDescription("GET /opportunities/search."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/opportunities/search", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("opportunities_update_opportunities",
			mcplib.WithDescription("PUT /opportunities/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/opportunities/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("payments_create_coupons",
			mcplib.WithDescription("POST /payments/coupons. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/payments/coupons", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("payments_delete_coupons",
			mcplib.WithDescription("DELETE /payments/coupons/{id}. Required: id. Optional: params. Destructive."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/payments/coupons/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("payments_get_coupons",
			mcplib.WithDescription("GET /payments/coupons/{id}. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/payments/coupons/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("payments_get_orders",
			mcplib.WithDescription("GET /payments/orders/{id}. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/payments/orders/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("payments_list_coupons",
			mcplib.WithDescription("GET /payments/coupons. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/payments/coupons", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("payments_list_orders",
			mcplib.WithDescription("GET /payments/orders. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/payments/orders", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("payments_list_subscriptions",
			mcplib.WithDescription("GET /payments/subscriptions. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/payments/subscriptions", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("payments_list_transactions",
			mcplib.WithDescription("GET /payments/transactions. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/payments/transactions", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("payments_update_coupons",
			mcplib.WithDescription("PUT /payments/coupons/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/payments/coupons/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("social-media-posting_create_social_media_posting",
			mcplib.WithDescription("POST /social-media-posting. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/social-media-posting", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("social-media-posting_delete_social_media_posting",
			mcplib.WithDescription("DELETE /social-media-posting/{id}. Required: id. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/social-media-posting/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("social-media-posting_get_social_media_posting",
			mcplib.WithDescription("GET /social-media-posting/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/social-media-posting/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("social-media-posting_list_social_media_posting",
			mcplib.WithDescription("GET /social-media-posting. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/social-media-posting", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("surveys_list_submissions",
			mcplib.WithDescription("GET /surveys/submissions. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/surveys/submissions", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("surveys_list_surveys",
			mcplib.WithDescription("GET /surveys. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/surveys", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("users_get_users",
			mcplib.WithDescription("GET /users/{id}. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/users/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("users_list_users",
			mcplib.WithDescription("GET /users. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/users", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("webhooks_create_webhooks",
			mcplib.WithDescription("POST /webhooks. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/webhooks", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("webhooks_delete_webhooks",
			mcplib.WithDescription("DELETE /webhooks/{id}. Required: id. Optional: params. Destructive."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/webhooks/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("webhooks_get_webhooks",
			mcplib.WithDescription("GET /webhooks/{id}. Required: id. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/webhooks/{id}", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("webhooks_list_webhooks",
			mcplib.WithDescription("GET /webhooks. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/webhooks", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("webhooks_update_webhooks",
			mcplib.WithDescription("PUT /webhooks/{id}. Required: id. Optional: body."),
			mcplib.WithString("body", mcplib.Description("")),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PUT", "/webhooks/{id}", []mcpParamBinding{{PublicName: "body", WireName: "body", Location: "query"},{PublicName: "id", WireName: "id", Location: "path"}, }, []string{"id", }),
	)
	s.AddTool(
		mcplib.NewTool("workflows_list_workflows",
			mcplib.WithDescription("GET /workflows. Optional: params."),
			mcplib.WithString("params", mcplib.Description("")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/workflows", []mcpParamBinding{{PublicName: "params", WireName: "params", Location: "query"}, }, []string{ }),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export SCALIFY_TOKEN=<your-key>" +
					"\n      Run 'scalify-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export SCALIFY_TOKEN=<your-key>" +
					"\n      Run 'scalify-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export SCALIFY_TOKEN=<your-key>" +
					"\n      Run 'scalify-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "scalify-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "scalify-pp-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "scalify",
		"description": "Scalify Platform API",
		"archetype":   "content",
		"tool_count":  121,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion scalify-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name": "SCALIFY_TOKEN",
					"kind": "per_call",
					"required": true,
					"sensitive": true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name": "blogs",
				"description": "Operations on posts",
				"endpoints": []string{"get_posts", "list_authors", "list_categories", "list_posts", "list_url_slug_exists",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "businesses",
				"description": "Operations on businesses",
				"endpoints": []string{"create_businesses", "delete_businesses", "get_businesses", "list_businesses", "update_businesses",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "calendars",
				"description": "Operations on calendars",
				"endpoints": []string{"create_appointments", "create_calendars", "delete_calendars", "get_calendars", "get_free_slots", "list_calendars", "list_events", "update_calendars",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "campaigns",
				"description": "Operations on campaigns",
				"endpoints": []string{"list_campaigns",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "contacts",
				"description": "Operations on contacts",
				"endpoints": []string{"create_contacts", "create_notes", "create_tags", "create_tasks", "create_upsert", "create_workflow", "delete_contacts", "delete_tags", "get_appointments", "get_contacts", "get_notes", "get_tasks", "list_contacts", "update_contacts",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "conversations",
				"description": "Operations on search",
				"endpoints": []string{"create_conversations", "create_inbound", "create_messages", "get_conversations", "get_messages", "get_messages_2", "list_search", "update_status",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "courses",
				"description": "Operations on courses",
				"endpoints": []string{"list_courses",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "documents",
				"description": "Operations on documents",
				"endpoints": []string{"create_send", "delete_documents", "get_documents", "list_documents",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "emails",
				"description": "Operations on emails",
				"endpoints": []string{"list_emails",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "forms",
				"description": "Operations on forms",
				"endpoints": []string{"list_forms", "list_submissions",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "funnels",
				"description": "Operations on list",
				"endpoints": []string{"list_funnels", "list_list", "list_page",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "invoices",
				"description": "Operations on invoices",
				"endpoints": []string{"create_estimate", "create_invoices", "create_record_payment", "create_send", "create_send_2", "create_void", "delete_estimate", "delete_invoices", "get_estimate", "get_invoices", "list_estimate", "list_invoices", "update_estimate", "update_invoices",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "links",
				"description": "Operations on links",
				"endpoints": []string{"list_links",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "locations",
				"description": "Operations on locations",
				"endpoints": []string{"create_customFields", "create_customValues", "create_tags", "delete_customFields", "delete_customValues", "delete_tags", "get_customFields", "get_customValues", "get_locations", "get_tags", "list_locations", "list_search", "update_customFields", "update_customValues", "update_locations", "update_tags",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "medias",
				"description": "Operations on files",
				"endpoints": []string{"delete_medias", "list_files",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "objects",
				"description": "Operations on objects",
				"endpoints": []string{"create_records", "delete_records", "get_objects", "get_records", "get_records_2", "list_objects", "update_records",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "opportunities",
				"description": "Operations on search",
				"endpoints": []string{"create_opportunities", "delete_opportunities", "get_opportunities", "list_pipelines", "list_search", "update_opportunities",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "payments",
				"description": "Operations on orders",
				"endpoints": []string{"create_coupons", "delete_coupons", "get_coupons", "get_orders", "list_coupons", "list_orders", "list_subscriptions", "list_transactions", "update_coupons",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "social-media-posting",
				"description": "Operations on social-media-posting",
				"endpoints": []string{"create_social_media_posting", "delete_social_media_posting", "get_social_media_posting", "list_social_media_posting",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "surveys",
				"description": "Operations on surveys",
				"endpoints": []string{"list_submissions", "list_surveys",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "users",
				"description": "Operations on users",
				"endpoints": []string{"get_users", "list_users",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "webhooks",
				"description": "Operations on webhooks",
				"endpoints": []string{"create_webhooks", "delete_webhooks", "get_webhooks", "list_webhooks", "update_webhooks",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "workflows",
				"description": "Operations on workflows",
				"endpoints": []string{"list_workflows",  },
				"syncable": true,
				"searchable": true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
