// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBusinessesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "businesses",
		Short: "Operations on businesses",
	}

	cmd.AddCommand(newBusinessesCreateBusinessesCmd(flags))
	cmd.AddCommand(newBusinessesDeleteBusinessesCmd(flags))
	cmd.AddCommand(newBusinessesGetBusinessesCmd(flags))
	cmd.AddCommand(newBusinessesListBusinessesCmd(flags))
	cmd.AddCommand(newBusinessesUpdateBusinessesCmd(flags))
	return cmd
}
