// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCalendarsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "calendars",
		Short: "Operations on calendars",
	}

	cmd.AddCommand(newCalendarsCreateAppointmentsCmd(flags))
	cmd.AddCommand(newCalendarsCreateCalendarsCmd(flags))
	cmd.AddCommand(newCalendarsDeleteCalendarsCmd(flags))
	cmd.AddCommand(newCalendarsGetCalendarsCmd(flags))
	cmd.AddCommand(newCalendarsGetFreeSlotsCmd(flags))
	cmd.AddCommand(newCalendarsListCalendarsCmd(flags))
	cmd.AddCommand(newCalendarsListEventsCmd(flags))
	cmd.AddCommand(newCalendarsUpdateCalendarsCmd(flags))
	return cmd
}
