// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContactsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "contacts",
		Short: "Operations on contacts",
	}

	cmd.AddCommand(newContactsCreateContactsCmd(flags))
	cmd.AddCommand(newContactsCreateNotesCmd(flags))
	cmd.AddCommand(newContactsCreateTagsCmd(flags))
	cmd.AddCommand(newContactsCreateTasksCmd(flags))
	cmd.AddCommand(newContactsCreateUpsertCmd(flags))
	cmd.AddCommand(newContactsCreateWorkflowCmd(flags))
	cmd.AddCommand(newContactsDeleteContactsCmd(flags))
	cmd.AddCommand(newContactsDeleteTagsCmd(flags))
	cmd.AddCommand(newContactsGetAppointmentsCmd(flags))
	cmd.AddCommand(newContactsGetContactsCmd(flags))
	cmd.AddCommand(newContactsGetNotesCmd(flags))
	cmd.AddCommand(newContactsGetTasksCmd(flags))
	cmd.AddCommand(newContactsListContactsCmd(flags))
	cmd.AddCommand(newContactsUpdateContactsCmd(flags))
	return cmd
}
