// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newConversationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "conversations",
		Short: "Operations on search",
	}

	cmd.AddCommand(newConversationsCreateConversationsCmd(flags))
	cmd.AddCommand(newConversationsCreateInboundCmd(flags))
	cmd.AddCommand(newConversationsCreateMessagesCmd(flags))
	cmd.AddCommand(newConversationsGetConversationsCmd(flags))
	cmd.AddCommand(newConversationsGetMessagesCmd(flags))
	cmd.AddCommand(newConversationsGetMessages2Cmd(flags))
	cmd.AddCommand(newConversationsListSearchCmd(flags))
	cmd.AddCommand(newConversationsUpdateStatusCmd(flags))
	return cmd
}
