// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDocumentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "documents",
		Short: "Operations on documents",
	}

	cmd.AddCommand(newDocumentsCreateSendCmd(flags))
	cmd.AddCommand(newDocumentsDeleteDocumentsCmd(flags))
	cmd.AddCommand(newDocumentsGetDocumentsCmd(flags))
	cmd.AddCommand(newDocumentsListDocumentsCmd(flags))
	return cmd
}
