// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFormsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "forms",
		Short: "Operations on forms",
	}

	cmd.AddCommand(newFormsListFormsCmd(flags))
	cmd.AddCommand(newFormsListSubmissionsCmd(flags))
	return cmd
}
