// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFunnelsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "funnels",
		Short: "Operations on list",
	}

	cmd.AddCommand(newFunnelsListFunnelsCmd(flags))
	cmd.AddCommand(newFunnelsListListCmd(flags))
	cmd.AddCommand(newFunnelsListPageCmd(flags))
	return cmd
}
