// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInvoicesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "invoices",
		Short: "Operations on invoices",
	}

	cmd.AddCommand(newInvoicesCreateEstimateCmd(flags))
	cmd.AddCommand(newInvoicesCreateInvoicesCmd(flags))
	cmd.AddCommand(newInvoicesCreateRecordPaymentCmd(flags))
	cmd.AddCommand(newInvoicesCreateSendCmd(flags))
	cmd.AddCommand(newInvoicesCreateSend2Cmd(flags))
	cmd.AddCommand(newInvoicesCreateVoidCmd(flags))
	cmd.AddCommand(newInvoicesDeleteEstimateCmd(flags))
	cmd.AddCommand(newInvoicesDeleteInvoicesCmd(flags))
	cmd.AddCommand(newInvoicesGetEstimateCmd(flags))
	cmd.AddCommand(newInvoicesGetInvoicesCmd(flags))
	cmd.AddCommand(newInvoicesListEstimateCmd(flags))
	cmd.AddCommand(newInvoicesListInvoicesCmd(flags))
	cmd.AddCommand(newInvoicesUpdateEstimateCmd(flags))
	cmd.AddCommand(newInvoicesUpdateInvoicesCmd(flags))
	return cmd
}
