// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLocationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "locations",
		Short: "Operations on locations",
	}

	cmd.AddCommand(newLocationsCreateCustomFieldsCmd(flags))
	cmd.AddCommand(newLocationsCreateCustomValuesCmd(flags))
	cmd.AddCommand(newLocationsCreateTagsCmd(flags))
	cmd.AddCommand(newLocationsDeleteCustomFieldsCmd(flags))
	cmd.AddCommand(newLocationsDeleteCustomValuesCmd(flags))
	cmd.AddCommand(newLocationsDeleteTagsCmd(flags))
	cmd.AddCommand(newLocationsGetCustomFieldsCmd(flags))
	cmd.AddCommand(newLocationsGetCustomValuesCmd(flags))
	cmd.AddCommand(newLocationsGetLocationsCmd(flags))
	cmd.AddCommand(newLocationsGetTagsCmd(flags))
	cmd.AddCommand(newLocationsListLocationsCmd(flags))
	cmd.AddCommand(newLocationsListSearchCmd(flags))
	cmd.AddCommand(newLocationsUpdateCustomFieldsCmd(flags))
	cmd.AddCommand(newLocationsUpdateCustomValuesCmd(flags))
	cmd.AddCommand(newLocationsUpdateLocationsCmd(flags))
	cmd.AddCommand(newLocationsUpdateTagsCmd(flags))
	return cmd
}
