// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newObjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "objects",
		Short: "Operations on objects",
	}

	cmd.AddCommand(newObjectsCreateRecordsCmd(flags))
	cmd.AddCommand(newObjectsDeleteRecordsCmd(flags))
	cmd.AddCommand(newObjectsGetObjectsCmd(flags))
	cmd.AddCommand(newObjectsGetRecordsCmd(flags))
	cmd.AddCommand(newObjectsGetRecords2Cmd(flags))
	cmd.AddCommand(newObjectsListObjectsCmd(flags))
	cmd.AddCommand(newObjectsUpdateRecordsCmd(flags))
	return cmd
}
