// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOpportunitiesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "opportunities",
		Short: "Operations on search",
	}

	cmd.AddCommand(newOpportunitiesCreateOpportunitiesCmd(flags))
	cmd.AddCommand(newOpportunitiesDeleteOpportunitiesCmd(flags))
	cmd.AddCommand(newOpportunitiesGetOpportunitiesCmd(flags))
	cmd.AddCommand(newOpportunitiesListPipelinesCmd(flags))
	cmd.AddCommand(newOpportunitiesListSearchCmd(flags))
	cmd.AddCommand(newOpportunitiesUpdateOpportunitiesCmd(flags))
	return cmd
}
