// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPaymentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "payments",
		Short: "Operations on orders",
	}

	cmd.AddCommand(newPaymentsCreateCouponsCmd(flags))
	cmd.AddCommand(newPaymentsDeleteCouponsCmd(flags))
	cmd.AddCommand(newPaymentsGetCouponsCmd(flags))
	cmd.AddCommand(newPaymentsGetOrdersCmd(flags))
	cmd.AddCommand(newPaymentsListCouponsCmd(flags))
	cmd.AddCommand(newPaymentsListOrdersCmd(flags))
	cmd.AddCommand(newPaymentsListSubscriptionsCmd(flags))
	cmd.AddCommand(newPaymentsListTransactionsCmd(flags))
	cmd.AddCommand(newPaymentsUpdateCouponsCmd(flags))
	return cmd
}
