// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSocialMediaPostingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "social-media-posting",
		Short: "Operations on social-media-posting",
	}

	cmd.AddCommand(newSocialMediaPostingCreateSocialMediaPostingCmd(flags))
	cmd.AddCommand(newSocialMediaPostingDeleteSocialMediaPostingCmd(flags))
	cmd.AddCommand(newSocialMediaPostingGetSocialMediaPostingCmd(flags))
	cmd.AddCommand(newSocialMediaPostingListSocialMediaPostingCmd(flags))
	return cmd
}
