// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSurveysCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "surveys",
		Short: "Operations on surveys",
	}

	cmd.AddCommand(newSurveysListSubmissionsCmd(flags))
	cmd.AddCommand(newSurveysListSurveysCmd(flags))
	return cmd
}
