// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWebhooksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "webhooks",
		Short: "Operations on webhooks",
	}

	cmd.AddCommand(newWebhooksCreateWebhooksCmd(flags))
	cmd.AddCommand(newWebhooksDeleteWebhooksCmd(flags))
	cmd.AddCommand(newWebhooksGetWebhooksCmd(flags))
	cmd.AddCommand(newWebhooksListWebhooksCmd(flags))
	cmd.AddCommand(newWebhooksUpdateWebhooksCmd(flags))
	return cmd
}
