// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "blogs get_posts", Description: "GET /blogs/{id}/posts/{id}", Group: "blogs"},
	{Command: "blogs list_authors", Description: "GET /blogs/authors", Group: "blogs"},
	{Command: "blogs list_categories", Description: "GET /blogs/categories", Group: "blogs"},
	{Command: "blogs list_posts", Description: "GET /blogs/posts", Group: "blogs"},
	{Command: "blogs list_url_slug_exists", Description: "GET /blogs/posts/url-slug-exists", Group: "blogs"},
	{Command: "businesses create_businesses", Description: "POST /businesses", Group: "businesses"},
	{Command: "businesses delete_businesses", Description: "DELETE /businesses/{id}", Group: "businesses"},
	{Command: "businesses get_businesses", Description: "GET /businesses/{id}", Group: "businesses"},
	{Command: "businesses list_businesses", Description: "GET /businesses", Group: "businesses"},
	{Command: "businesses update_businesses", Description: "PUT /businesses/{id}", Group: "businesses"},
	{Command: "calendars create_appointments", Description: "POST /calendars/events/appointments", Group: "calendars"},
	{Command: "calendars create_calendars", Description: "POST /calendars", Group: "calendars"},
	{Command: "calendars delete_calendars", Description: "DELETE /calendars/{id}", Group: "calendars"},
	{Command: "calendars get_calendars", Description: "GET /calendars/{id}", Group: "calendars"},
	{Command: "calendars get_free_slots", Description: "GET /calendars/{id}/free-slots", Group: "calendars"},
	{Command: "calendars list_calendars", Description: "GET /calendars", Group: "calendars"},
	{Command: "calendars list_events", Description: "GET /calendars/events", Group: "calendars"},
	{Command: "calendars update_calendars", Description: "PUT /calendars/{id}", Group: "calendars"},
	{Command: "campaigns list_campaigns", Description: "GET /campaigns", Group: "campaigns"},
	{Command: "contacts create_contacts", Description: "POST /contacts", Group: "contacts"},
	{Command: "contacts create_notes", Description: "POST /contacts/{id}/notes", Group: "contacts"},
	{Command: "contacts create_tags", Description: "POST /contacts/{id}/tags", Group: "contacts"},
	{Command: "contacts create_tasks", Description: "POST /contacts/{id}/tasks", Group: "contacts"},
	{Command: "contacts create_upsert", Description: "POST /contacts/upsert", Group: "contacts"},
	{Command: "contacts create_workflow", Description: "POST /contacts/{id}/workflow/{id}", Group: "contacts"},
	{Command: "contacts delete_contacts", Description: "DELETE /contacts/{id}", Group: "contacts"},
	{Command: "contacts delete_tags", Description: "DELETE /contacts/{id}/tags", Group: "contacts"},
	{Command: "contacts get_appointments", Description: "GET /contacts/{id}/appointments", Group: "contacts"},
	{Command: "contacts get_contacts", Description: "GET /contacts/{id}", Group: "contacts"},
	{Command: "contacts get_notes", Description: "GET /contacts/{id}/notes", Group: "contacts"},
	{Command: "contacts get_tasks", Description: "GET /contacts/{id}/tasks", Group: "contacts"},
	{Command: "contacts list_contacts", Description: "GET /contacts", Group: "contacts"},
	{Command: "contacts update_contacts", Description: "PUT /contacts/{id}", Group: "contacts"},
	{Command: "conversations create_conversations", Description: "POST /conversations", Group: "conversations"},
	{Command: "conversations create_inbound", Description: "POST /conversations/messages/inbound", Group: "conversations"},
	{Command: "conversations create_messages", Description: "POST /conversations/messages", Group: "conversations"},
	{Command: "conversations get_conversations", Description: "GET /conversations/{id}", Group: "conversations"},
	{Command: "conversations get_messages", Description: "GET /conversations/{id}/messages", Group: "conversations"},
	{Command: "conversations get_messages_2", Description: "GET /conversations/messages/{id}", Group: "conversations"},
	{Command: "conversations list_search", Description: "GET /conversations/search", Group: "conversations"},
	{Command: "conversations update_status", Description: "PUT /conversations/messages/{id}/status", Group: "conversations"},
	{Command: "courses list_courses", Description: "GET /courses", Group: "courses"},
	{Command: "documents create_send", Description: "POST /documents/{id}/send", Group: "documents"},
	{Command: "documents delete_documents", Description: "DELETE /documents/{id}", Group: "documents"},
	{Command: "documents get_documents", Description: "GET /documents/{id}", Group: "documents"},
	{Command: "documents list_documents", Description: "GET /documents", Group: "documents"},
	{Command: "emails list_emails", Description: "GET /emails", Group: "emails"},
	{Command: "forms list_forms", Description: "GET /forms", Group: "forms"},
	{Command: "forms list_submissions", Description: "GET /forms/submissions", Group: "forms"},
	{Command: "funnels list_funnels", Description: "GET /funnels", Group: "funnels"},
	{Command: "funnels list_list", Description: "GET /funnels/funnel/list", Group: "funnels"},
	{Command: "funnels list_page", Description: "GET /funnels/page", Group: "funnels"},
	{Command: "invoices create_estimate", Description: "POST /invoices/estimate", Group: "invoices"},
	{Command: "invoices create_invoices", Description: "POST /invoices", Group: "invoices"},
	{Command: "invoices create_record_payment", Description: "POST /invoices/{id}/record-payment", Group: "invoices"},
	{Command: "invoices create_send", Description: "POST /invoices/{id}/send", Group: "invoices"},
	{Command: "invoices create_send_2", Description: "POST /invoices/estimate/{id}/send", Group: "invoices"},
	{Command: "invoices create_void", Description: "POST /invoices/{id}/void", Group: "invoices"},
	{Command: "invoices delete_estimate", Description: "DELETE /invoices/estimate/{id}", Group: "invoices"},
	{Command: "invoices delete_invoices", Description: "DELETE /invoices/{id}", Group: "invoices"},
	{Command: "invoices get_estimate", Description: "GET /invoices/estimate/{id}", Group: "invoices"},
	{Command: "invoices get_invoices", Description: "GET /invoices/{id}", Group: "invoices"},
	{Command: "invoices list_estimate", Description: "GET /invoices/estimate", Group: "invoices"},
	{Command: "invoices list_invoices", Description: "GET /invoices", Group: "invoices"},
	{Command: "invoices update_estimate", Description: "PUT /invoices/estimate/{id}", Group: "invoices"},
	{Command: "invoices update_invoices", Description: "PUT /invoices/{id}", Group: "invoices"},
	{Command: "links list_links", Description: "GET /links", Group: "links"},
	{Command: "locations create_customFields", Description: "POST /locations/{id}/customFields", Group: "locations"},
	{Command: "locations create_customValues", Description: "POST /locations/{id}/customValues", Group: "locations"},
	{Command: "locations create_tags", Description: "POST /locations/{id}/tags", Group: "locations"},
	{Command: "locations delete_customFields", Description: "DELETE /locations/{id}/customFields/{id}", Group: "locations"},
	{Command: "locations delete_customValues", Description: "DELETE /locations/{id}/customValues/{id}", Group: "locations"},
	{Command: "locations delete_tags", Description: "DELETE /locations/{id}/tags/{id}", Group: "locations"},
	{Command: "locations get_customFields", Description: "GET /locations/{id}/customFields", Group: "locations"},
	{Command: "locations get_customValues", Description: "GET /locations/{id}/customValues", Group: "locations"},
	{Command: "locations get_locations", Description: "GET /locations/{id}", Group: "locations"},
	{Command: "locations get_tags", Description: "GET /locations/{id}/tags", Group: "locations"},
	{Command: "locations list_locations", Description: "GET /locations", Group: "locations"},
	{Command: "locations list_search", Description: "GET /locations/search", Group: "locations"},
	{Command: "locations update_customFields", Description: "PUT /locations/{id}/customFields/{id}", Group: "locations"},
	{Command: "locations update_customValues", Description: "PUT /locations/{id}/customValues/{id}", Group: "locations"},
	{Command: "locations update_locations", Description: "PUT /locations/{id}", Group: "locations"},
	{Command: "locations update_tags", Description: "PUT /locations/{id}/tags/{id}", Group: "locations"},
	{Command: "medias delete_medias", Description: "DELETE /medias/{id}", Group: "medias"},
	{Command: "medias list_files", Description: "GET /medias/files", Group: "medias"},
	{Command: "objects create_records", Description: "POST /objects/{id}/records", Group: "objects"},
	{Command: "objects delete_records", Description: "DELETE /objects/{id}/records/{id}", Group: "objects"},
	{Command: "objects get_objects", Description: "GET /objects/{id}", Group: "objects"},
	{Command: "objects get_records", Description: "GET /objects/{id}/records", Group: "objects"},
	{Command: "objects get_records_2", Description: "GET /objects/{id}/records/{id}", Group: "objects"},
	{Command: "objects list_objects", Description: "GET /objects", Group: "objects"},
	{Command: "objects update_records", Description: "PUT /objects/{id}/records/{id}", Group: "objects"},
	{Command: "opportunities create_opportunities", Description: "POST /opportunities", Group: "opportunities"},
	{Command: "opportunities delete_opportunities", Description: "DELETE /opportunities/{id}", Group: "opportunities"},
	{Command: "opportunities get_opportunities", Description: "GET /opportunities/{id}", Group: "opportunities"},
	{Command: "opportunities list_pipelines", Description: "GET /opportunities/pipelines", Group: "opportunities"},
	{Command: "opportunities list_search", Description: "GET /opportunities/search", Group: "opportunities"},
	{Command: "opportunities update_opportunities", Description: "PUT /opportunities/{id}", Group: "opportunities"},
	{Command: "payments create_coupons", Description: "POST /payments/coupons", Group: "payments"},
	{Command: "payments delete_coupons", Description: "DELETE /payments/coupons/{id}", Group: "payments"},
	{Command: "payments get_coupons", Description: "GET /payments/coupons/{id}", Group: "payments"},
	{Command: "payments get_orders", Description: "GET /payments/orders/{id}", Group: "payments"},
	{Command: "payments list_coupons", Description: "GET /payments/coupons", Group: "payments"},
	{Command: "payments list_orders", Description: "GET /payments/orders", Group: "payments"},
	{Command: "payments list_subscriptions", Description: "GET /payments/subscriptions", Group: "payments"},
	{Command: "payments list_transactions", Description: "GET /payments/transactions", Group: "payments"},
	{Command: "payments update_coupons", Description: "PUT /payments/coupons/{id}", Group: "payments"},
	{Command: "social-media-posting create_social_media_posting", Description: "POST /social-media-posting", Group: "social-media-posting"},
	{Command: "social-media-posting delete_social_media_posting", Description: "DELETE /social-media-posting/{id}", Group: "social-media-posting"},
	{Command: "social-media-posting get_social_media_posting", Description: "GET /social-media-posting/{id}", Group: "social-media-posting"},
	{Command: "social-media-posting list_social_media_posting", Description: "GET /social-media-posting", Group: "social-media-posting"},
	{Command: "surveys list_submissions", Description: "GET /surveys/submissions", Group: "surveys"},
	{Command: "surveys list_surveys", Description: "GET /surveys", Group: "surveys"},
	{Command: "users get_users", Description: "GET /users/{id}", Group: "users"},
	{Command: "users list_users", Description: "GET /users", Group: "users"},
	{Command: "webhooks create_webhooks", Description: "POST /webhooks", Group: "webhooks"},
	{Command: "webhooks delete_webhooks", Description: "DELETE /webhooks/{id}", Group: "webhooks"},
	{Command: "webhooks get_webhooks", Description: "GET /webhooks/{id}", Group: "webhooks"},
	{Command: "webhooks list_webhooks", Description: "GET /webhooks", Group: "webhooks"},
	{Command: "webhooks update_webhooks", Description: "PUT /webhooks/{id}", Group: "webhooks"},
	{Command: "workflows list_workflows", Description: "GET /workflows", Group: "workflows"},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  scalify-pp-cli which "stale tickets"
  scalify-pp-cli which "bottleneck"
  scalify-pp-cli which --limit 1 "send message"
  scalify-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
