// Copyright 2026 scalify. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
)

// AuthScheme is the token format prefix; dogfood and scorecard use this constant
// to verify the generated client matches the spec's securitySchemes declaration.
const AuthScheme = "Bearer"

type Config struct {
	BaseURL        string `toml:"base_url"`
	AuthHeaderVal  string `toml:"auth_header"`
	Headers        map[string]string `toml:"headers,omitempty"`
	AuthSource     string `toml:"-"`
	AccessToken    string `toml:"access_token"`
	RefreshToken   string `toml:"refresh_token"`
	TokenExpiry    time.Time `toml:"token_expiry"`
	ClientID       string `toml:"client_id"`
	ClientSecret   string `toml:"client_secret"`
	Path           string `toml:"-"`
	ScalifyToken   string            `toml:"token"`
	LocationID     string            `toml:"location_id"`
	LocationTokens map[string]string `toml:"location_tokens,omitempty"`
	LocationNames  map[string]string `toml:"location_names,omitempty"`
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://services.leadconnectorhq.com",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("SCALIFY_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "scalify-pp-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides
	if v := os.Getenv("SCALIFY_LOCATION_ID"); v != "" {
		cfg.LocationID = v
	}
	if v := os.Getenv("SCALIFY_TOKEN"); v != "" {
		cfg.ScalifyToken = v
		cfg.AuthSource = "env:SCALIFY_TOKEN"
	}

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "" || cfg.AccessToken != "") {
		cfg.AuthSource = "config"
	}
	if cfg.AuthSource == "" && cfg.ScalifyToken != "" {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("SCALIFY_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	// Env-var token wins over file-stored AccessToken (env > config convention).
	if c.ScalifyToken != "" {
		c.AuthSource = "env:SCALIFY_TOKEN"
		return applyAuthFormat("Bearer {token}", map[string]string{
			"token": c.ScalifyToken,
			"SCALIFY_TOKEN": c.ScalifyToken,
		})
	}
	if c.AccessToken != "" {
		c.AuthSource = "oauth2"
		return applyAuthFormat("Bearer {token}", map[string]string{"access_token": c.AccessToken, "token": c.AccessToken})
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) SaveTokens(clientID, clientSecret, accessToken, refreshToken string, expiry time.Time) error {
	c.ClientID = clientID
	c.ClientSecret = clientSecret
	c.AccessToken = accessToken
	c.RefreshToken = refreshToken
	c.TokenExpiry = expiry
	return c.save()
}

func (c *Config) SaveLocation(id, name, token string) error {
	c.LocationID = id
	if token != "" {
		if c.LocationTokens == nil {
			c.LocationTokens = map[string]string{}
		}
		c.LocationTokens[id] = token
	}
	if name != "" {
		if c.LocationNames == nil {
			c.LocationNames = map[string]string{}
		}
		c.LocationNames[id] = name
	}
	// Load saved token for this location into active credentials
	if saved, ok := c.LocationTokens[id]; ok {
		c.AccessToken = saved
		c.AuthHeaderVal = ""
	}
	return c.save()
}

func (c *Config) AddLocation(id, name, token string) error {
	if c.LocationTokens == nil {
		c.LocationTokens = map[string]string{}
	}
	c.LocationTokens[id] = token
	if name != "" {
		if c.LocationNames == nil {
			c.LocationNames = map[string]string{}
		}
		c.LocationNames[id] = name
	}
	return c.save()
}

// ResolveLocation returns the location ID for the given name-or-ID string.
// If the input matches a saved name, the corresponding ID is returned.
// Otherwise the input is returned as-is (assumed to already be an ID).
func (c *Config) ResolveLocation(nameOrID string) string {
	for id, name := range c.LocationNames {
		if name == nameOrID {
			return id
		}
	}
	return nameOrID
}

func (c *Config) ClearTokens() error {
	c.AccessToken = ""
	c.RefreshToken = ""
	c.TokenExpiry = time.Time{}
	return c.save()
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

// Ensure strings import is used
var _ = strings.ReplaceAll
